default:
  golem_name: shiny.app.nba
  golem_version: 0.0.0.9000
  app_prod: no
  team: "LAL"
  season: "2015 - 2016"
  team_color_1: "#552583"
  team_color_2: "#FDB927"
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
